backend:
  name: git-gateway
  branch: master
locale: "ja"
media_folder: static/images/uploads

collections:
  - name: "blog"
    label: "Blog"
    folder: "content/blog"
    create: true
    slug: "{{title}}--{{date}}"
    preview_path: "blog/{{fields.slug}}"
    fields:
      - {
          label: "Template Key",
          name: "templateKey",
          widget: "hidden",
          default: "blog-post",
        }
      - { label: "タイトル", name: "title", widget: "string" }
      - { label: "概要", name: "description", widget: "string" }
      - {
          label: "投稿者",
          name: "contributor",
          widget: "select",
          options:
            [
              "採用担当",
              "広報部",
              "デザイン部",
              "開発部 マミミ",
              "開発部 ハナ",
            ],
        }
      - { label: "アイコン色", name: "color", widget: "color" }
      - { label: "本文", name: "body", widget: "markdown" }
      - { label: "カテゴリー", name: "tags", widget: "list" }
      - { label: "投稿時刻", name: "date", widget: "datetime" }
      - { label: "アイキャッチイメージ", name: "featuredimage", widget: image }
